/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.leansoft.logging.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum LogLevel implements org.apache.thrift.TEnum {
  DEBUG(0),
  INFO(1),
  WARN(2),
  ERROR(3),
  FATAL(4);

  private final int value;

  private LogLevel(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static LogLevel findByValue(int value) { 
    switch (value) {
      case 0:
        return DEBUG;
      case 1:
        return INFO;
      case 2:
        return WARN;
      case 3:
        return ERROR;
      case 4:
        return FATAL;
      default:
        return null;
    }
  }
}
